/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class mpi_eudico_client_annotator_viewer_PraatConnection */

#ifndef _Included_mpi_eudico_client_annotator_viewer_PraatConnection
#define _Included_mpi_eudico_client_annotator_viewer_PraatConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpi_eudico_client_annotator_viewer_PraatConnection
 * Method:    sendpraatNative
 * Signature: (Ljava/lang/String;JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mpi_eudico_client_annotator_viewer_PraatConnection_sendpraatNative
  (JNIEnv *, jclass, jstring, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
