/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_mpi_jds_JDSPlayer */

#ifndef _Included_nl_mpi_jds_JDSPlayer
#define _Included_nl_mpi_jds_JDSPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef nl_mpi_jds_JDSPlayer_MS_TO_REF_TIME
#define nl_mpi_jds_JDSPlayer_MS_TO_REF_TIME 10000L
#undef nl_mpi_jds_JDSPlayer_AUDIO_BALANCE_FACTOR
#define nl_mpi_jds_JDSPlayer_AUDIO_BALANCE_FACTOR 10000L
#undef nl_mpi_jds_JDSPlayer_STATE_STOP
#define nl_mpi_jds_JDSPlayer_STATE_STOP 0L
#undef nl_mpi_jds_JDSPlayer_STATE_PAUSE
#define nl_mpi_jds_JDSPlayer_STATE_PAUSE 1L
#undef nl_mpi_jds_JDSPlayer_STATE_RUN
#define nl_mpi_jds_JDSPlayer_STATE_RUN 2L
/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    pause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_pause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    isPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_mpi_jds_JDSPlayer_isPlaying
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    stopWhenReady
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_stopWhenReady
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_jds_JDSPlayer_getState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setRate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setRate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getRate
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_nl_mpi_jds_JDSPlayer_getRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setVolume
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setVolume
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getVolume
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_nl_mpi_jds_JDSPlayer_getVolume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setBalance
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setBalance
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getBalance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_jds_JDSPlayer_getBalance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setMediaTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setMediaTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getMediaTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_jds_JDSPlayer_getMediaTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_jds_JDSPlayer_getDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_nl_mpi_jds_JDSPlayer_getFrameRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getTimePerFrame
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_nl_mpi_jds_JDSPlayer_getTimePerFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getAspectRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_nl_mpi_jds_JDSPlayer_getAspectRatio
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getOriginalSize
 * Signature: (J)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_nl_mpi_jds_JDSPlayer_getOriginalSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setVisualComponent
 * Signature: (JLjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setVisualComponent
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setVisualComponentPos
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setVisualComponentPos
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setVisible
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setVideoSourcePos
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setVideoSourcePos
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setVideoDestinationPos
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setVideoDestinationPos
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getVideoDestinationPos
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_nl_mpi_jds_JDSPlayer_getVideoDestinationPos
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    initWithFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_jds_JDSPlayer_initWithFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    initWithFileAndCodec
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_jds_JDSPlayer_initWithFileAndCodec
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    isCodecInstalled
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_mpi_jds_JDSPlayer_isCodecInstalled
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getRegisteredFilters
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_mpi_jds_JDSPlayer_getRegisteredFilters
  (JNIEnv *, jobject);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getFiltersInGraph
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_nl_mpi_jds_JDSPlayer_getFiltersInGraph
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getFileType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_mpi_jds_JDSPlayer_getFileType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    isVisualMedia
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_mpi_jds_JDSPlayer_isVisualMedia
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    setStopTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_setStopTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getStopTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_jds_JDSPlayer_getStopTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getSourceHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_jds_JDSPlayer_getSourceHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getSourceWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_jds_JDSPlayer_getSourceWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getPreferredAspectRatio
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_nl_mpi_jds_JDSPlayer_getPreferredAspectRatio
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getCurrentImage
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_mpi_jds_JDSPlayer_getCurrentImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    getImageAtTime
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_mpi_jds_JDSPlayer_getImageAtTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    enableDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_enableDebugMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     nl_mpi_jds_JDSPlayer
 * Method:    clean
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_jds_JDSPlayer_clean
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
