/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_mpi_avf_player_JAVFPlayer */

#ifndef _Included_nl_mpi_avf_player_JAVFPlayer
#define _Included_nl_mpi_avf_player_JAVFPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    initPlayer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_avf_player_JAVFPlayer_initPlayer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    deletePlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_avf_player_JAVFPlayer_deletePlayer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    getBytesPerRow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_avf_player_JAVFPlayer_getBytesPerRow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    getBytesPerPixel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_avf_player_JAVFPlayer_getBytesPerPixel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    getVideoImageWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_avf_player_JAVFPlayer_getVideoImageWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    getVideoImageHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_nl_mpi_avf_player_JAVFPlayer_getVideoImageHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    getPixelFormat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_mpi_avf_player_JAVFPlayer_getPixelFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    setPixelFormat
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_mpi_avf_player_JAVFPlayer_setPixelFormat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    getVideoFrameSequence
 * Signature: (JJJLjava/nio/ByteBuffer;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_nl_mpi_avf_player_JAVFPlayer_getVideoFrameSequence
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     nl_mpi_avf_player_JAVFPlayer
 * Method:    getVideoFrameSequenceSeconds
 * Signature: (JDDLjava/nio/ByteBuffer;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_nl_mpi_avf_player_JAVFPlayer_getVideoFrameSequenceSeconds
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jobject);

#ifdef __cplusplus
}
#endif
#endif
