/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_mpi_avf_player_JAVFLogLevel */

#ifndef _Included_nl_mpi_avf_player_JAVFLogLevel
#define _Included_nl_mpi_avf_player_JAVFLogLevel
#ifdef __cplusplus
extern "C" {
#endif
#undef nl_mpi_avf_player_JAVFLogLevel_ALL
#define nl_mpi_avf_player_JAVFLogLevel_ALL 0L
#undef nl_mpi_avf_player_JAVFLogLevel_FINE
#define nl_mpi_avf_player_JAVFLogLevel_FINE 3L
#undef nl_mpi_avf_player_JAVFLogLevel_INFO
#define nl_mpi_avf_player_JAVFLogLevel_INFO 5L
#undef nl_mpi_avf_player_JAVFLogLevel_WARNING
#define nl_mpi_avf_player_JAVFLogLevel_WARNING 8L
#undef nl_mpi_avf_player_JAVFLogLevel_OFF
#define nl_mpi_avf_player_JAVFLogLevel_OFF 10L
#ifdef __cplusplus
}
#endif
#endif
