/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_mpi_avf_player_AVFNativePlayer */

#ifndef _Included_nl_mpi_avf_player_AVFNativePlayer
#define _Included_nl_mpi_avf_player_AVFNativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    initPlayer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_initPlayer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    deletePlayer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_deletePlayer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    setVisualComponent
 * Signature: (JLjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_setVisualComponent
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    disconnectVisualComponent
 * Signature: (JLjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_disconnectVisualComponent
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    setVideoScaleFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_setVideoScaleFactor
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    setVideoBounds
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_setVideoBounds
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    getVideoBounds
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_getVideoBounds
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nl_mpi_avf_player_AVFNativePlayer
 * Method:    repaintVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nl_mpi_avf_player_AVFNativePlayer_repaintVideo
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
